package com.ayushtech.flagbot.services;

import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.TimeUnit;

import com.ayushtech.flagbot.dbconnectivity.LanguageDao;

import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.Permission;
import net.dv8tion.jda.api.events.interaction.command.SlashCommandInteractionEvent;

public class LanguageService {
  private static LanguageService languageService = null;
  private Map<Long, String> serverLanguageMapping;
  private Map<String, String> arabicMap;
  private Map<String, String> spanishMap;
  private Map<String, String> portugueseMap;
  private Map<String, String> japaneseMap;
  private Map<String, String> koreanMap;
  private Map<String, String> turkishMap;
  private Map<String, Map<String, String>> languageMap;

  private LanguageService() {
    serverLanguageMapping = LanguageDao.getInstance().getLanguageMap();
    arabicMap = new HashMap<>(267);
    spanishMap = new HashMap<>(267);
    portugueseMap = new HashMap<>(267);
    japaneseMap = new HashMap<>(267);
    koreanMap = new HashMap<>(267);
    turkishMap = new HashMap<>(267);
    languageMap = new HashMap<>();
    loadArabicCountries();
    loadSpanishCountries();
    loadJapaneseCountries();
    loadPortugueseCountries();
    loadKoreanCountries();
    loadTurkishCountries();
    loadLanguageMap();
  }

  private void loadLanguageMap() {
    languageMap.put("arabic", arabicMap);
    languageMap.put("spanish", spanishMap);
    languageMap.put("japanese", japaneseMap);
    languageMap.put("portuguese", portugueseMap);
    languageMap.put("korean", koreanMap);
    languageMap.put("turkish", turkishMap);
  }

  public static LanguageService getInstance() {
    if (languageService == null) {
      languageService = new LanguageService();
    }
    return languageService;
  }

  public void handleLanguageCommand(SlashCommandInteractionEvent event) {
    String subcommandName = event.getSubcommandName();
    switch (subcommandName) {
      case "info":
        sendLanguageInformation(event);
        return;
      case "set":
        setLanguage(event);
        return;
      case "remove":
        removeLanguage(event);
        return;
      default:
        event.getHook().sendMessage("Something went wrong!").queue();
    }
  }

  public boolean isGuessRight(String language, String guess, String countryCode) {
    if (language == null) {
      return false;
    }
    return languageMap.get(language).get(countryCode).equalsIgnoreCase(guess);
  }

  public Optional<String> getLanguageSelected(long serverId) {
    if (serverLanguageMapping.containsKey(serverId)) {
      return Optional.of(serverLanguageMapping.get(serverId));
    } else {
      return Optional.empty();
    }
  }

  public String getCorrectGuess(String language, String countryCode) {
    return languageMap.get(language).get(countryCode);
  }

  private void removeLanguage(SlashCommandInteractionEvent event) {
    boolean isFromGuild = event.isFromGuild();
    if (!isFromGuild) {
      event.getHook().sendMessage("This command only work in a guild").queue();
      return;
    }
    if (event.getMember().hasPermission(Permission.MANAGE_SERVER)) {
      long guildId = event.getGuild().getIdLong();
      if (serverLanguageMapping.containsKey(guildId)) {
        serverLanguageMapping.remove(guildId);
        LanguageDao.getInstance().removeGuildLanguage(guildId);
        EmbedBuilder eb = new EmbedBuilder();
        eb.setColor(Color.green);
        eb.setDescription("Removed server language");
        event.getHook().sendMessageEmbeds(eb.build()).queue();
      } else {
        event.getHook().sendMessage("No language selected!").queue(
            m -> m.delete().queueAfter(15, TimeUnit.SECONDS));
      }
    } else {
      event.getHook().sendMessage("You need `MANAGE_SERVER` permissions to remove language.")
          .queue(m -> m.delete().queueAfter(15, TimeUnit.SECONDS));
      return;
    }
  }

  private void setLanguage(SlashCommandInteractionEvent event) {
    boolean isFromGuild = event.isFromGuild();
    if (!isFromGuild) {
      event.getHook().sendMessage("This command only work in a guild").queue();
      return;
    }
    if (event.getMember().hasPermission(Permission.MANAGE_SERVER)) {
      String language = event.getOption("language").getAsString().toLowerCase();
      if (languageMap.containsKey(language)) {
        long guildId = event.getGuild().getIdLong();
        serverLanguageMapping.put(guildId, language);
        LanguageDao.getInstance().setGuildLanguage(guildId, language);
        EmbedBuilder eb = new EmbedBuilder();
        eb.setColor(Color.green);
        eb.setTitle("Language");
        eb.setDescription("Language selected : `" + language.toUpperCase() + "`");
        event.getHook().sendMessageEmbeds(eb.build()).queue();
      } else {
        event.getHook()
            .sendMessage("The following language : `" + language
                + "` is not supported!\nDo `/language info` to see the supported languages")
            .queue(m -> m.delete().queueAfter(10, TimeUnit.SECONDS));
      }
    } else {
      event.getHook().sendMessage("You need `MANAGE_SERVER` permissions to change language.")
          .queue(m -> m.delete().queueAfter(15, TimeUnit.SECONDS));
    }
  }

  private void sendLanguageInformation(SlashCommandInteractionEvent event) {
    boolean isFromGuild = event.isFromGuild();
    if (!isFromGuild) {
      event.getHook().sendMessage("This command only work in a guild!").queue();
      return;
    }
    long serverId = event.getGuild().getIdLong();
    EmbedBuilder eb = new EmbedBuilder();
    eb.setTitle("Languages");
    eb.setColor(Color.YELLOW);
    boolean isLanguageSelected = serverLanguageMapping.containsKey(serverId);
    if (isLanguageSelected) {
      eb.setDescription("__Selected Language__ : `" + serverLanguageMapping.get(serverId).toUpperCase() + "`");
    } else {
      eb.setDescription("No language selected for this server");
    }
    eb.addField("__Supported Languages__", "`Arabic`, `Japanese`, `Korean`, `Portuguese`, `Spanish`, `Turkish`", false);
    event.getHook().sendMessageEmbeds(eb.build()).queue();
  }

  private void loadTurkishCountries() {
    turkishMap.put("aa", "Saba");
    turkishMap.put("ab", "Abhazya");
    turkishMap.put("ay", "Adıge");
    turkishMap.put("aj", "Acara");
    turkishMap.put("ald", "Alderney");
    turkishMap.put("alr", "Altay Cumhuriyeti");
    turkishMap.put("ad", "Andorra");
    turkishMap.put("ae", "Birleşik Arap Emirlikleri");
    turkishMap.put("af", "Afganistan");
    turkishMap.put("ag", "Antigua ve Barbuda");
    turkishMap.put("ai", "Anguilla");
    turkishMap.put("al", "Arnavutluk");
    turkishMap.put("am", "Ermenistan");
    turkishMap.put("ao", "Angola");
    turkishMap.put("aq", "Antarktika");
    turkishMap.put("an", "Antarktika");
    turkishMap.put("ar", "Arjantin");
    turkishMap.put("as", "Amerikan Samoası");
    turkishMap.put("at", "Avusturya");
    turkishMap.put("au", "Avustralya");
    turkishMap.put("aw", "Aruba");
    turkishMap.put("ax", "Aland adaları");
    turkishMap.put("az", "Azerbaycan");
    turkishMap.put("ba", "Bosna Hersek");
    turkishMap.put("bb", "Barbados");
    turkishMap.put("bd", "Bangladeş");
    turkishMap.put("be", "Belçika");
    turkishMap.put("bf", "Burkina Faso");
    turkishMap.put("bg", "Bulgaristan");
    turkishMap.put("bh", "Bahreyn");
    turkishMap.put("bi", "Burundi");
    turkishMap.put("bj", "Benin");
    turkishMap.put("bl", "Aziz Barthelemy");
    turkishMap.put("bm", "Bermuda");
    turkishMap.put("bn", "Brunei");
    turkishMap.put("bo", "Bolivya");
    turkishMap.put("bq", "Karayip Hollandası");
    turkishMap.put("baq", "İngiliz Antarktika");
    turkishMap.put("br", "Brezilya");
    turkishMap.put("bs", "Bahamalar");
    turkishMap.put("bt", "Butan");
    turkishMap.put("bv", "Bouvet Adası");
    turkishMap.put("bw", "Botsvana");
    turkishMap.put("by", "Belarus");
    turkishMap.put("bz", "Belize");
    turkishMap.put("ca", "Kanada");
    turkishMap.put("cc", "Cocos Adaları");
    turkishMap.put("cd", "Kongo Demokratik Cumhuriyeti");
    turkishMap.put("cf", "Orta Afrika Cumhuriyeti");
    turkishMap.put("cg", "Kongo");
    turkishMap.put("ch", "İsviçre");
    turkishMap.put("ci", "Fildişi Sahili");
    turkishMap.put("ck", "Cook Adaları");
    turkishMap.put("cl", "Şili");
    turkishMap.put("cm", "Kamerun");
    turkishMap.put("cn", "Çin");
    turkishMap.put("co", "Kolombiya");
    turkishMap.put("cr", "Kosta Rika");
    turkishMap.put("cu", "Küba");
    turkishMap.put("cv", "Yeşil Burun Adaları");
    turkishMap.put("cw", "Curacao");
    turkishMap.put("cx", "Noel Adası");
    turkishMap.put("cy", "Kıbrıs");
    turkishMap.put("cz", "Çek Cumhuriyeti");
    turkishMap.put("de", "Almanya");
    turkishMap.put("dj", "Cibuti");
    turkishMap.put("dk", "Danimarka");
    turkishMap.put("dm", "Dominika");
    turkishMap.put("do", "Dominik Cumhuriyeti");
    turkishMap.put("dz", "Cezayir");
    turkishMap.put("ec", "Ekvador");
    turkishMap.put("ee", "Estonya");
    turkishMap.put("eg", "Mısır");
    turkishMap.put("eh", "Batı Sahra");
    turkishMap.put("ei", "Sint Eustatius");
    turkishMap.put("er", "Eritre");
    turkishMap.put("es", "ispanya");
    turkishMap.put("et", "Etiyopya");
    turkishMap.put("fi", "Finlandiya");
    turkishMap.put("fj", "Fiji");
    turkishMap.put("fk", "Falkland adaları");
    turkishMap.put("fm", "Mikronezya");
    turkishMap.put("fo", "Faroe Adaları");
    turkishMap.put("fr", "Fransa");
    turkishMap.put("ga", "Gabon");
    turkishMap.put("gb", "Birleşik Krallık");
    turkishMap.put("gb-eng", "İngiltere");
    turkishMap.put("gb-nir", "Kuzey Irlanda");
    turkishMap.put("gb-sct", "İskoçya");
    turkishMap.put("gb-wls", "Galler");
    turkishMap.put("gd", "Grenada");
    turkishMap.put("ge", "Gürcistan");
    turkishMap.put("gf", "Fransız Guyanası");
    turkishMap.put("gg", "Guernsey");
    turkishMap.put("gh", "Gana");
    turkishMap.put("gi", "Cebelitarık");
    turkishMap.put("gl", "Grönland");
    turkishMap.put("gm", "Gambiya");
    turkishMap.put("gn", "Gine");
    turkishMap.put("gp", "Guadeloupe");
    turkishMap.put("gq", "Ekvator Ginesi");
    turkishMap.put("gr", "Yunanistan");
    turkishMap.put("gs", "Güney Georgia ve Güney Sandwich Adaları");
    turkishMap.put("gt", "Guatemala");
    turkishMap.put("gu", "Guam");
    turkishMap.put("gw", "Gine-Bissau");
    turkishMap.put("gy", "Guyana");
    turkishMap.put("hk", "Hong Kong");
    turkishMap.put("hm", "Heard Adası ve McDonald Adaları");
    turkishMap.put("hn", "Honduras");
    turkishMap.put("hr", "Hırvatistan");
    turkishMap.put("ht", "Haiti");
    turkishMap.put("hu", "Macaristan");
    turkishMap.put("id", "Endonezya");
    turkishMap.put("ie", "İrlanda");
    turkishMap.put("il", "İsrail");
    turkishMap.put("im", "Man Adası");
    turkishMap.put("in", "Hindistan");
    turkishMap.put("io", "Britanya Hint Okyanusu Bölgesi");
    turkishMap.put("iq", "Irak");
    turkishMap.put("ir", "İran");
    turkishMap.put("is", "İzlanda");
    turkishMap.put("it", "İtalya");
    turkishMap.put("je", "Jersey");
    turkishMap.put("jm", "Jamaika");
    turkishMap.put("jo", "Ürdün");
    turkishMap.put("jp", "Japonya");
    turkishMap.put("ke", "Kenya");
    turkishMap.put("kg", "Kırgızistan");
    turkishMap.put("kh", "Kamboçya");
    turkishMap.put("ki", "Kiribati");
    turkishMap.put("km", "Komorlar");
    turkishMap.put("kn", "Saint Kitts ve Nevis");
    turkishMap.put("kp", "Kuzey Kore");
    turkishMap.put("kr", "Güney Kore");
    turkishMap.put("kw", "Kuveyt");
    turkishMap.put("ky", "Cayman Adaları");
    turkishMap.put("kz", "Kazakistan");
    turkishMap.put("la", "Laos");
    turkishMap.put("lb", "Lübnan");
    turkishMap.put("lc", "Aziz Lucia");
    turkishMap.put("li", "Lihtenştayn");
    turkishMap.put("lk", "Sri Lanka");
    turkishMap.put("lr", "Liberya");
    turkishMap.put("ls", "Lesoto");
    turkishMap.put("lt", "Litvanya");
    turkishMap.put("lu", "Lüksemburg");
    turkishMap.put("lv", "Letonya");
    turkishMap.put("ly", "Libya");
    turkishMap.put("ma", "Fas");
    turkishMap.put("mc", "Monako");
    turkishMap.put("md", "Moldova");
    turkishMap.put("me", "Karadağ");
    turkishMap.put("mf", "Aziz Martin");
    turkishMap.put("mg", "Madagaskar");
    turkishMap.put("mh", "Marşal Adaları");
    turkishMap.put("mk", "Kuzey Makedonya");
    turkishMap.put("ml", "Mali");
    turkishMap.put("mm", "Myanmar");
    turkishMap.put("mn", "Moğolistan");
    turkishMap.put("mo", "Makao");
    turkishMap.put("mp", "Kuzey Mariana Adaları");
    turkishMap.put("mq", "Martinik");
    turkishMap.put("mi", "Martinik");
    turkishMap.put("mr", "Moritanya");
    turkishMap.put("ms", "Montserrat");
    turkishMap.put("mt", "Malta");
    turkishMap.put("mu", "Mauritius");
    turkishMap.put("mv", "Maldivler");
    turkishMap.put("mw", "Malawi");
    turkishMap.put("mx", "Meksika");
    turkishMap.put("my", "Malezya");
    turkishMap.put("mz", "Mozambik");
    turkishMap.put("na", "Namibya");
    turkishMap.put("nc", "Yeni Kaledonya");
    turkishMap.put("ne", "Nijer");
    turkishMap.put("nf", "Norfolk Adası");
    turkishMap.put("ng", "Nijerya");
    turkishMap.put("ni", "Nikaragua");
    turkishMap.put("nl", "Hollanda");
    turkishMap.put("no", "Norveç");
    turkishMap.put("np", "Nepal");
    turkishMap.put("nr", "Nauru'lu");
    turkishMap.put("nu", "Niue");
    turkishMap.put("nz", "Yeni Zelanda");
    turkishMap.put("om", "Umman");
    turkishMap.put("pa", "Panama");
    turkishMap.put("pe", "Peru");
    turkishMap.put("pf", "Fransız Polinezyası");
    turkishMap.put("pg", "Papua Yeni Gine");
    turkishMap.put("ph", "Filipinler");
    turkishMap.put("pk", "Pakistan");
    turkishMap.put("pl", "Polonya");
    turkishMap.put("pm", "Saint Pierre ve Miquelon");
    turkishMap.put("pn", "Pitcairn Adaları");
    turkishMap.put("pr", "Porto Riko");
    turkishMap.put("ps", "Filistin");
    turkishMap.put("pt", "Portekiz");
    turkishMap.put("pw", "Palau");
    turkishMap.put("py", "Paraguay");
    turkishMap.put("qa", "Katar");
    turkishMap.put("re", "Yeniden Birleşme");
    turkishMap.put("ro", "Romanya");
    turkishMap.put("rs", "Sırbistan");
    turkishMap.put("ru", "Rusya");
    turkishMap.put("rw", "Ruanda");
    turkishMap.put("sa", "Suudi Arabistan");
    turkishMap.put("sb", "Solomon Adaları");
    turkishMap.put("sc", "Seyşeller");
    turkishMap.put("sd", "Sudan");
    turkishMap.put("se", "İsveç");
    turkishMap.put("sg", "Singapur");
    turkishMap.put("sh", "Aziz Helena");
    turkishMap.put("si", "Slovenya");
    turkishMap.put("sj", "Svalbard ve Jan Mayen");
    turkishMap.put("sk", "Slovakya");
    turkishMap.put("sl", "Sierra Leone");
    turkishMap.put("sm", "San Marino");
    turkishMap.put("sn", "Senegal");
    turkishMap.put("so", "Somali");
    turkishMap.put("sr", "Surinam");
    turkishMap.put("ss", "Güney Sudan");
    turkishMap.put("st", "Sao Tome ve Principe");
    turkishMap.put("sv", "El Salvador");
    turkishMap.put("sx", "Sint Maarten");
    turkishMap.put("sy", "Suriye");
    turkishMap.put("sz", "Esvatini");
    turkishMap.put("tc", "Turks ve Caicos Adaları");
    turkishMap.put("td", "Çad");
    turkishMap.put("tf", "Fransız Güney ve Antarktika Toprakları");
    turkishMap.put("tg", "Gitmek");
    turkishMap.put("th", "Tayland");
    turkishMap.put("tj", "Tacikistan");
    turkishMap.put("tk", "Tokelau");
    turkishMap.put("tl", "Doğu Timor");
    turkishMap.put("tm", "Türkmenistan");
    turkishMap.put("tn", "Tunus");
    turkishMap.put("to", "Tonga");
    turkishMap.put("tr", "Türkiye");
    turkishMap.put("tt", "Trinidad ve Tobago");
    turkishMap.put("tv", "Tuvalu");
    turkishMap.put("tw", "Tayvan");
    turkishMap.put("tz", "Tanzanya");
    turkishMap.put("ua", "Ukrayna");
    turkishMap.put("ug", "Uganda");
    turkishMap.put("um", "Amerika Birleşik Devletleri Küçük Dış Adaları");
    turkishMap.put("us", "Amerika Birleşik Devletleri");
    turkishMap.put("uy", "Uruguay");
    turkishMap.put("uz", "Özbekistan");
    turkishMap.put("va", "Vatikan Şehri");
    turkishMap.put("vc", "Saint Vincent ve Grenadinler");
    turkishMap.put("ve", "Venezuela");
    turkishMap.put("vg", "Britanya Virjin Adaları");
    turkishMap.put("vi", "Amerika Birleşik Devletleri Virgin Adaları");
    turkishMap.put("vn", "Vietnam");
    turkishMap.put("vu", "Vanuatu");
    turkishMap.put("wf", "Wallis ve Futuna");
    turkishMap.put("ws", "Samoa");
    turkishMap.put("xk", "Kosova");
    turkishMap.put("ye", "Yemen");
    turkishMap.put("yt", "Mayotte");
    turkishMap.put("za", "Güney Afrika");
    turkishMap.put("zm", "Zambiya");
    turkishMap.put("zw", "Zimbabve");
    turkishMap.put("ac", "Yükseliş");
    turkishMap.put("ti", "Tristan da Cunha");
    turkishMap.put("bas", "Başkurdistan");
    turkishMap.put("bia", "Bikini Mercan Adası");
    turkishMap.put("bri", "Britanya");
    turkishMap.put("bur", "Buryatia");
    turkishMap.put("cri", "Çeçen İçkerya Cumhuriyeti");
    turkishMap.put("che", "Çeçen Cumhuriyeti");
    turkishMap.put("chu", "Çuvaşistan");
    turkishMap.put("crm", "Kırım");
    turkishMap.put("eai", "Paskalya Adası");
    turkishMap.put("dag", "Dağıstan");
    turkishMap.put("eu", "Avrupa Birliği");
    turkishMap.put("her", "Herm");
    turkishMap.put("ing", "İnguşetya");
    turkishMap.put("kpr", "Kuban Halk Cumhuriyeti");
    turkishMap.put("kab", "Kabardey-Balkar");
    turkishMap.put("kal", "Kalmıkya");
    turkishMap.put("kar", "Karaçay-Çerkesya");
    turkishMap.put("kkp", "Karakalpakstan");
    turkishMap.put("krl", "Karelya");
    turkishMap.put("kha", "Hakasya");
    turkishMap.put("kom", "Komi");
    turkishMap.put("ala", "Alaska");
  }

  private void loadKoreanCountries() {
    koreanMap.put("aa", "사바");
    koreanMap.put("ab", "압하지야");
    koreanMap.put("ay", "아디게아");
    koreanMap.put("aj", "아자리야");
    koreanMap.put("ald", "올더니");
    koreanMap.put("alr", "알타이 공화국");
    koreanMap.put("ad", "안도라");
    koreanMap.put("ae", "아랍 에미리트");
    koreanMap.put("af", "아프가니스탄");
    koreanMap.put("ag", "앤티가 바부다");
    koreanMap.put("ai", "앵귈라");
    koreanMap.put("al", "알바니아");
    koreanMap.put("am", "아르메니아");
    koreanMap.put("ao", "앙골라");
    koreanMap.put("aq", "남극 대륙");
    koreanMap.put("an", "남극 대륙");
    koreanMap.put("ar", "아르헨티나");
    koreanMap.put("as", "아메리칸사모아");
    koreanMap.put("at", "오스트리아");
    koreanMap.put("au", "호주");
    koreanMap.put("aw", "아루바");
    koreanMap.put("ax", "올란드 제도");
    koreanMap.put("az", "아제르바이잔");
    koreanMap.put("ba", "보스니아 헤르체고비나");
    koreanMap.put("bb", "바베이도스");
    koreanMap.put("bd", "방글라데시");
    koreanMap.put("be", "벨기에");
    koreanMap.put("bf", "부키 나 파소");
    koreanMap.put("bg", "불가리아");
    koreanMap.put("bh", "바레인");
    koreanMap.put("bi", "부룬디");
    koreanMap.put("bj", "베냉");
    koreanMap.put("bl", "생바르텔레미");
    koreanMap.put("bm", "버뮤다");
    koreanMap.put("bn", "브루나이");
    koreanMap.put("bo", "볼리비아");
    koreanMap.put("bq", "카리브해 네덜란드");
    koreanMap.put("baq", "영국 남극");
    koreanMap.put("br", "브라질");
    koreanMap.put("bs", "바하마");
    koreanMap.put("bt", "부탄");
    koreanMap.put("bv", "부베섬");
    koreanMap.put("bw", "보츠와나");
    koreanMap.put("by", "벨라루스");
    koreanMap.put("bz", "벨리즈");
    koreanMap.put("ca", "캐나다");
    koreanMap.put("cc", "코코스 제도");
    koreanMap.put("cd", "콩고민주공화국");
    koreanMap.put("cf", "중앙 아프리카 공화국");
    koreanMap.put("cg", "콩고");
    koreanMap.put("ch", "스위스");
    koreanMap.put("ci", "아이보리 해안");
    koreanMap.put("ck", "쿡 제도");
    koreanMap.put("cl", "칠레");
    koreanMap.put("cm", "카메룬");
    koreanMap.put("cn", "중국");
    koreanMap.put("co", "콜롬비아");
    koreanMap.put("cr", "코스타리카");
    koreanMap.put("cu", "쿠바");
    koreanMap.put("cv", "카보베르데");
    koreanMap.put("cw", "퀴라소");
    koreanMap.put("cx", "크리스마스 섬");
    koreanMap.put("cy", "키프로스");
    koreanMap.put("cz", "체코 공화국");
    koreanMap.put("de", "독일");
    koreanMap.put("dj", "지부티");
    koreanMap.put("dk", "덴마크");
    koreanMap.put("dm", "도미니카");
    koreanMap.put("do", "도미니카 공화국");
    koreanMap.put("dz", "알제리");
    koreanMap.put("ec", "에콰도르");
    koreanMap.put("ee", "에스토니아");
    koreanMap.put("eg", "이집트");
    koreanMap.put("eh", "서부 사하라");
    koreanMap.put("ei", "신트 유스타티우스");
    koreanMap.put("er", "에리트레아");
    koreanMap.put("es", "스페인");
    koreanMap.put("et", "에티오피아");
    koreanMap.put("fi", "핀란드");
    koreanMap.put("fj", "피지");
    koreanMap.put("fk", "포클랜드 제도");
    koreanMap.put("fm", "미크로네시아");
    koreanMap.put("fo", "페로 제도");
    koreanMap.put("fr", "프랑스");
    koreanMap.put("ga", "가봉");
    koreanMap.put("gb", "영국");
    koreanMap.put("gb-eng", "영국");
    koreanMap.put("gb-nir", "북아일랜드");
    koreanMap.put("gb-sct", "스코틀랜드");
    koreanMap.put("gb-wls", "웨일즈");
    koreanMap.put("gd", "그레나다");
    koreanMap.put("ge", "그루지야");
    koreanMap.put("gf", "프랑스령 기아나");
    koreanMap.put("gg", "건지");
    koreanMap.put("gh", "가나");
    koreanMap.put("gi", "지브롤터");
    koreanMap.put("gl", "그린란드");
    koreanMap.put("gm", "감비아");
    koreanMap.put("gn", "기니");
    koreanMap.put("gp", "과들루프");
    koreanMap.put("gq", "적도 기니");
    koreanMap.put("gr", "그리스");
    koreanMap.put("gs", "사우스조지아 사우스샌드위치 제도");
    koreanMap.put("gt", "과테말라");
    koreanMap.put("gu", "괌");
    koreanMap.put("gw", "기니비사우");
    koreanMap.put("gy", "가이아나");
    koreanMap.put("hk", "홍콩");
    koreanMap.put("hm", "허드섬과 맥도날드 제도");
    koreanMap.put("hn", "온두라스");
    koreanMap.put("hr", "크로아티아");
    koreanMap.put("ht", "아이티");
    koreanMap.put("hu", "헝가리");
    koreanMap.put("id", "인도네시아");
    koreanMap.put("ie", "아일랜드");
    koreanMap.put("il", "이스라엘");
    koreanMap.put("im", "맨 섬");
    koreanMap.put("in", "인도");
    koreanMap.put("io", "영국령 인도양 지역");
    koreanMap.put("iq", "이라크");
    koreanMap.put("ir", "이란");
    koreanMap.put("is", "아이슬란드");
    koreanMap.put("it", "이탈리아");
    koreanMap.put("je", "저지");
    koreanMap.put("jm", "자메이카");
    koreanMap.put("jo", "요르단");
    koreanMap.put("jp", "일본");
    koreanMap.put("ke", "케냐");
    koreanMap.put("kg", "키르기스스탄");
    koreanMap.put("kh", "캄보디아");
    koreanMap.put("ki", "키리바시");
    koreanMap.put("km", "코모로");
    koreanMap.put("kn", "세인트키츠네비스");
    koreanMap.put("kp", "북한");
    koreanMap.put("kr", "대한민국");
    koreanMap.put("kw", "쿠웨이트");
    koreanMap.put("ky", "케이맨 제도");
    koreanMap.put("kz", "카자흐스탄");
    koreanMap.put("la", "라오스");
    koreanMap.put("lb", "레바논");
    koreanMap.put("lc", "세인트 루시아");
    koreanMap.put("li", "리히텐슈타인");
    koreanMap.put("lk", "스리랑카");
    koreanMap.put("lr", "라이베리아");
    koreanMap.put("ls", "레소토");
    koreanMap.put("lt", "리투아니아");
    koreanMap.put("lu", "룩셈부르크");
    koreanMap.put("lv", "라트비아");
    koreanMap.put("ly", "리비아");
    koreanMap.put("ma", "모로코");
    koreanMap.put("mc", "모나코");
    koreanMap.put("md", "몰도바");
    koreanMap.put("me", "몬테네그로");
    koreanMap.put("mf", "세인트 마틴");
    koreanMap.put("mg", "마다가스카르");
    koreanMap.put("mh", "마샬 군도");
    koreanMap.put("mk", "북 마케도니아");
    koreanMap.put("ml", "말리");
    koreanMap.put("mm", "미얀마");
    koreanMap.put("mn", "몽골리아");
    koreanMap.put("mo", "마카오");
    koreanMap.put("mp", "북마리아나 제도");
    koreanMap.put("mq", "마르티니크");
    koreanMap.put("mi", "마르티니크");
    koreanMap.put("mr", "모리타니");
    koreanMap.put("ms", "몬세라트");
    koreanMap.put("mt", "몰타");
    koreanMap.put("mu", "모리셔스");
    koreanMap.put("mv", "몰디브");
    koreanMap.put("mw", "말라위");
    koreanMap.put("mx", "멕시코");
    koreanMap.put("my", "말레이시아");
    koreanMap.put("mz", "모잠비크");
    koreanMap.put("na", "나미비아");
    koreanMap.put("nc", "뉴 칼레도니아");
    koreanMap.put("ne", "니제르");
    koreanMap.put("nf", "노퍽섬");
    koreanMap.put("ng", "나이지리아");
    koreanMap.put("ni", "니카라과");
    koreanMap.put("nl", "네덜란드");
    koreanMap.put("no", "노르웨이");
    koreanMap.put("np", "네팔");
    koreanMap.put("nr", "나우루");
    koreanMap.put("nu", "니우에");
    koreanMap.put("nz", "뉴질랜드");
    koreanMap.put("om", "오만");
    koreanMap.put("pa", "파나마");
    koreanMap.put("pe", "페루");
    koreanMap.put("pf", "프랑스 령 폴리네시아의");
    koreanMap.put("pg", "파푸아 뉴기니");
    koreanMap.put("ph", "필리핀 제도");
    koreanMap.put("pk", "파키스탄");
    koreanMap.put("pl", "폴란드");
    koreanMap.put("pm", "생 피에르 앤 미클롱");
    koreanMap.put("pn", "핏케언 제도");
    koreanMap.put("pr", "푸에르토 리코");
    koreanMap.put("ps", "팔레스타인");
    koreanMap.put("pt", "포르투갈");
    koreanMap.put("pw", "팔라우");
    koreanMap.put("py", "파라과이");
    koreanMap.put("qa", "카타르");
    koreanMap.put("re", "재결합");
    koreanMap.put("ro", "루마니아");
    koreanMap.put("rs", "세르비아");
    koreanMap.put("ru", "러시아");
    koreanMap.put("rw", "르완다");
    koreanMap.put("sa", "사우디 아라비아");
    koreanMap.put("sb", "솔로몬 제도");
    koreanMap.put("sc", "세이셸");
    koreanMap.put("sd", "수단");
    koreanMap.put("se", "스웨덴");
    koreanMap.put("sg", "싱가포르");
    koreanMap.put("sh", "세인트 헬레나");
    koreanMap.put("si", "슬로베니아");
    koreanMap.put("sj", "스발바르와 얀마옌");
    koreanMap.put("sk", "슬로바키아");
    koreanMap.put("sl", "시에라리온");
    koreanMap.put("sm", "산 마리노");
    koreanMap.put("sn", "세네갈");
    koreanMap.put("so", "소말리아");
    koreanMap.put("sr", "수리남");
    koreanMap.put("ss", "남 수단");
    koreanMap.put("st", "상투메 프린시페");
    koreanMap.put("sv", "엘살바도르");
    koreanMap.put("sx", "신트마르턴");
    koreanMap.put("sy", "시리아");
    koreanMap.put("sz", "에스와티니");
    koreanMap.put("tc", "터크스 케이커스 제도");
    koreanMap.put("td", "차드");
    koreanMap.put("tf", "프랑스 남부 및 남극 지역");
    koreanMap.put("tg", "토고");
    koreanMap.put("th", "태국");
    koreanMap.put("tj", "타지키스탄");
    koreanMap.put("tk", "토켈라우");
    koreanMap.put("tl", "동티모르");
    koreanMap.put("tm", "투르크메니스탄");
    koreanMap.put("tn", "튀니지");
    koreanMap.put("to", "통가");
    koreanMap.put("tr", "투르키예");
    koreanMap.put("tt", "트리니다드 토바고");
    koreanMap.put("tv", "투발루");
    koreanMap.put("tw", "대만");
    koreanMap.put("tz", "탄자니아");
    koreanMap.put("ua", "우크라이나");
    koreanMap.put("ug", "우간다");
    koreanMap.put("um", "미국령 군소 제도");
    koreanMap.put("us", "미국");
    koreanMap.put("uy", "우루과이");
    koreanMap.put("uz", "우즈베키스탄");
    koreanMap.put("va", "바티칸 시국");
    koreanMap.put("vc", "세인트 빈센트 그레나딘");
    koreanMap.put("ve", "베네수엘라");
    koreanMap.put("vg", "영국령 버진아일랜드");
    koreanMap.put("vi", "미국령 버진아일랜드");
    koreanMap.put("vn", "베트남");
    koreanMap.put("vu", "바누아투");
    koreanMap.put("wf", "월리스푸투나");
    koreanMap.put("ws", "사모아");
    koreanMap.put("xk", "코소보");
    koreanMap.put("ye", "예멘");
    koreanMap.put("yt", "마요트");
    koreanMap.put("za", "남아프리카");
    koreanMap.put("zm", "잠비아");
    koreanMap.put("zw", "짐바브웨");
    koreanMap.put("ac", "승천");
    koreanMap.put("ti", "트리스탄 다 쿠냐");
    koreanMap.put("bas", "바슈코르토스탄");
    koreanMap.put("bia", "비키니 환초");
    koreanMap.put("bri", "브리트니");
    koreanMap.put("bur", "부랴티아");
    koreanMap.put("cri", "체첸 이케리아 공화국");
    koreanMap.put("che", "체첸 공화국");
    koreanMap.put("chu", "추바시아");
    koreanMap.put("crm", "크리미아");
    koreanMap.put("eai", "이스터 섬");
    koreanMap.put("dag", "다게스탄");
    koreanMap.put("eu", "유럽 연합");
    koreanMap.put("her", "허름");
    koreanMap.put("ing", "인구세티아");
    koreanMap.put("kpr", "쿠반 인민공화국");
    koreanMap.put("kab", "카바르디노-발카리아");
    koreanMap.put("kal", "칼미키아");
    koreanMap.put("kar", "카라차이-체르케시아");
    koreanMap.put("kkp", "카라칼팍스탄");
    koreanMap.put("krl", "카렐리아");
    koreanMap.put("kha", "카카시아");
    koreanMap.put("kom", "코미");
    koreanMap.put("ala", "알래스카");
  }

  private void loadJapaneseCountries() {
    japaneseMap.put("aa", "サバ");
    japaneseMap.put("ab", "アブハジア");
    japaneseMap.put("ay", "アディゲ");
    japaneseMap.put("aj", "アジャラ");
    japaneseMap.put("ald", "オルダニー");
    japaneseMap.put("alr", "アルタイ共和国");
    japaneseMap.put("ad", "アンドラ");
    japaneseMap.put("ae", "アラブ首長国連邦");
    japaneseMap.put("af", "アフガニスタン");
    japaneseMap.put("ag", "アンティグアバーブーダ");
    japaneseMap.put("ai", "アンギラ");
    japaneseMap.put("al", "アルバニア");
    japaneseMap.put("am", "アルメニア");
    japaneseMap.put("ao", "アンゴラ");
    japaneseMap.put("aq", "南極大陸");
    japaneseMap.put("an", "南極大陸");
    japaneseMap.put("ar", "アルゼンチン");
    japaneseMap.put("as", "アメリカ領サモア");
    japaneseMap.put("at", "オーストリア");
    japaneseMap.put("au", "オーストラリア");
    japaneseMap.put("aw", "アルバ");
    japaneseMap.put("ax", "オーランド諸島");
    japaneseMap.put("az", "アゼルバイジャン");
    japaneseMap.put("ba", "ボスニア・ヘルツェゴビナ");
    japaneseMap.put("bb", "バルバドス");
    japaneseMap.put("bd", "バングラデシュ");
    japaneseMap.put("be", "ベルギー");
    japaneseMap.put("bf", "ブルキナファソ");
    japaneseMap.put("bg", "ブルガリア");
    japaneseMap.put("bh", "バーレーン");
    japaneseMap.put("bi", "ブルンジ");
    japaneseMap.put("bj", "ベナン");
    japaneseMap.put("bl", "サン・バルテルミ島");
    japaneseMap.put("bm", "バミューダ");
    japaneseMap.put("bn", "ブルネイ");
    japaneseMap.put("bo", "ボリビア");
    japaneseMap.put("bq", "カリブ海オランダ");
    japaneseMap.put("baq", "イギリスの南極");
    japaneseMap.put("br", "ブラジル");
    japaneseMap.put("bs", "バハマ");
    japaneseMap.put("bt", "ブータン");
    japaneseMap.put("bv", "ブーベ島");
    japaneseMap.put("bw", "ボツワナ");
    japaneseMap.put("by", "ベラルーシ");
    japaneseMap.put("bz", "ベリーズ");
    japaneseMap.put("ca", "カナダ");
    japaneseMap.put("cc", "ココス諸島");
    japaneseMap.put("cd", "コンゴ民主共和国");
    japaneseMap.put("cf", "中央アフリカ共和国");
    japaneseMap.put("cg", "コンゴ");
    japaneseMap.put("ch", "スイス");
    japaneseMap.put("ci", "コートジボワール");
    japaneseMap.put("ck", "クック諸島");
    japaneseMap.put("cl", "チリ");
    japaneseMap.put("cm", "カメルーン");
    japaneseMap.put("cn", "中国");
    japaneseMap.put("co", "コロンビア");
    japaneseMap.put("cr", "コスタリカ");
    japaneseMap.put("cu", "キューバ");
    japaneseMap.put("cv", "カーボベルデ");
    japaneseMap.put("cw", "キュラソー");
    japaneseMap.put("cx", "クリスマス島");
    japaneseMap.put("cy", "キプロス");
    japaneseMap.put("cz", "チェコ共和国");
    japaneseMap.put("de", "ドイツ");
    japaneseMap.put("dj", "ジブチ");
    japaneseMap.put("dk", "デンマーク");
    japaneseMap.put("dm", "ドミニカ");
    japaneseMap.put("do", "ドミニカ共和国");
    japaneseMap.put("dz", "アルジェリア");
    japaneseMap.put("ec", "エクアドル");
    japaneseMap.put("ee", "エストニア");
    japaneseMap.put("eg", "エジプト");
    japaneseMap.put("eh", "西サハラ");
    japaneseMap.put("ei", "シント・ユースタティウス");
    japaneseMap.put("er", "エリトリア");
    japaneseMap.put("es", "スペイン");
    japaneseMap.put("et", "エチオピア");
    japaneseMap.put("fi", "フィンランド");
    japaneseMap.put("fj", "フィジー");
    japaneseMap.put("fk", "フォークランド諸島");
    japaneseMap.put("fm", "ミクロネシア");
    japaneseMap.put("fo", "フェロー諸島");
    japaneseMap.put("fr", "フランス");
    japaneseMap.put("ga", "ガボン");
    japaneseMap.put("gb", "イギリス");
    japaneseMap.put("gb-eng", "イングランド");
    japaneseMap.put("gb-nir", "北アイルランド");
    japaneseMap.put("gb-sct", "スコットランド");
    japaneseMap.put("gb-wls", "ウェールズ");
    japaneseMap.put("gd", "グレナダ");
    japaneseMap.put("ge", "ジョージア");
    japaneseMap.put("gf", "フランス領ギアナ");
    japaneseMap.put("gg", "ガーンジー島");
    japaneseMap.put("gh", "ガーナ");
    japaneseMap.put("gi", "ジブラルタル");
    japaneseMap.put("gl", "グリーンランド");
    japaneseMap.put("gm", "ガンビア");
    japaneseMap.put("gn", "ギニア");
    japaneseMap.put("gp", "グアドループ");
    japaneseMap.put("gq", "赤道ギニア");
    japaneseMap.put("gr", "ギリシャ");
    japaneseMap.put("gs", "サウスジョージア島とサウスサンドイッチ諸島");
    japaneseMap.put("gt", "グアテマラ");
    japaneseMap.put("gu", "グアム");
    japaneseMap.put("gw", "ギニアビサウ");
    japaneseMap.put("gy", "ガイアナ");
    japaneseMap.put("hk", "香港");
    japaneseMap.put("hm", "ハード島とマクドナルド諸島");
    japaneseMap.put("hn", "ホンジュラス");
    japaneseMap.put("hr", "クロアチア");
    japaneseMap.put("ht", "ハイチ");
    japaneseMap.put("hu", "ハンガリー");
    japaneseMap.put("id", "インドネシア");
    japaneseMap.put("ie", "アイルランド");
    japaneseMap.put("il", "イスラエル");
    japaneseMap.put("im", "マン島");
    japaneseMap.put("in", "インド");
    japaneseMap.put("io", "英領インド洋領土");
    japaneseMap.put("iq", "イラク");
    japaneseMap.put("ir", "イラン");
    japaneseMap.put("is", "アイスランド");
    japaneseMap.put("it", "イタリア");
    japaneseMap.put("je", "ジャージー");
    japaneseMap.put("jm", "ジャマイカ");
    japaneseMap.put("jo", "ヨルダン");
    japaneseMap.put("jp", "日本");
    japaneseMap.put("ke", "ケニア");
    japaneseMap.put("kg", "キルギス");
    japaneseMap.put("kh", "カンボジア");
    japaneseMap.put("ki", "キリバス");
    japaneseMap.put("km", "コモロ");
    japaneseMap.put("kn", "セントクリストファー・ネイビス");
    japaneseMap.put("kp", "北朝鮮");
    japaneseMap.put("kr", "韓国");
    japaneseMap.put("kw", "クウェート");
    japaneseMap.put("ky", "ケイマン諸島");
    japaneseMap.put("kz", "カザフスタン");
    japaneseMap.put("la", "ラオス");
    japaneseMap.put("lb", "レバノン");
    japaneseMap.put("lc", "セントルシア");
    japaneseMap.put("li", "リヒテンシュタイン");
    japaneseMap.put("lk", "スリランカ");
    japaneseMap.put("lr", "リベリア");
    japaneseMap.put("ls", "レソト");
    japaneseMap.put("lt", "リトアニア");
    japaneseMap.put("lu", "ルクセンブルク");
    japaneseMap.put("lv", "ラトビア");
    japaneseMap.put("ly", "リビア");
    japaneseMap.put("ma", "モロッコ");
    japaneseMap.put("mc", "モナコ");
    japaneseMap.put("md", "モルドバ");
    japaneseMap.put("me", "モンテネグロ");
    japaneseMap.put("mf", "セント・マーチン島");
    japaneseMap.put("mg", "マダガスカル");
    japaneseMap.put("mh", "マーシャル諸島");
    japaneseMap.put("mk", "北マケドニア");
    japaneseMap.put("ml", "マリ");
    japaneseMap.put("mm", "ミャンマー");
    japaneseMap.put("mn", "モンゴル");
    japaneseMap.put("mo", "マカオ");
    japaneseMap.put("mp", "北マリアナ諸島");
    japaneseMap.put("mq", "マルティニーク");
    japaneseMap.put("mi", "マルティニーク");
    japaneseMap.put("mr", "モーリタニア");
    japaneseMap.put("ms", "モントセラト");
    japaneseMap.put("mt", "マルタ");
    japaneseMap.put("mu", "モーリシャス");
    japaneseMap.put("mv", "モルディブ");
    japaneseMap.put("mw", "マラウイ");
    japaneseMap.put("mx", "メキシコ");
    japaneseMap.put("my", "マレーシア");
    japaneseMap.put("mz", "モザンビーク");
    japaneseMap.put("na", "ナミビア");
    japaneseMap.put("nc", "ニューカレドニア");
    japaneseMap.put("ne", "ニジェール");
    japaneseMap.put("nf", "ノーフォーク島");
    japaneseMap.put("ng", "ナイジェリア");
    japaneseMap.put("ni", "ニカラグア");
    japaneseMap.put("nl", "オランダ");
    japaneseMap.put("no", "ノルウェー");
    japaneseMap.put("np", "ネパール");
    japaneseMap.put("nr", "ナウル");
    japaneseMap.put("nu", "ニウエ");
    japaneseMap.put("nz", "ニュージーランド");
    japaneseMap.put("om", "オマーン");
    japaneseMap.put("pa", "パナマ");
    japaneseMap.put("pe", "ペルー");
    japaneseMap.put("pf", "フランス領ポリネシア");
    japaneseMap.put("pg", "パプアニューギニア");
    japaneseMap.put("ph", "フィリピン");
    japaneseMap.put("pk", "パキスタン");
    japaneseMap.put("pl", "ポーランド");
    japaneseMap.put("pm", "サンピエール島ミクロン島");
    japaneseMap.put("pn", "ピトケアン諸島");
    japaneseMap.put("pr", "プエルトリコ");
    japaneseMap.put("ps", "パレスチナ");
    japaneseMap.put("pt", "ポルトガル");
    japaneseMap.put("pw", "パラオ");
    japaneseMap.put("py", "パラグアイ");
    japaneseMap.put("qa", "カタール");
    japaneseMap.put("re", "再会");
    japaneseMap.put("ro", "ルーマニア");
    japaneseMap.put("rs", "セルビア");
    japaneseMap.put("ru", "ロシア");
    japaneseMap.put("rw", "ルワンダ");
    japaneseMap.put("sa", "サウジアラビア");
    japaneseMap.put("sb", "ソロモン諸島");
    japaneseMap.put("sc", "セーシェル");
    japaneseMap.put("sd", "スーダン");
    japaneseMap.put("se", "スウェーデン");
    japaneseMap.put("sg", "シンガポール");
    japaneseMap.put("sh", "セントヘレナ");
    japaneseMap.put("si", "スロベニア");
    japaneseMap.put("sj", "スバールバル諸島とヤンマイエン島");
    japaneseMap.put("sk", "スロバキア");
    japaneseMap.put("sl", "シエラレオネ");
    japaneseMap.put("sm", "サンマリノ");
    japaneseMap.put("sn", "セネガル");
    japaneseMap.put("so", "ソマリア");
    japaneseMap.put("sr", "スリナム");
    japaneseMap.put("ss", "南スーダン");
    japaneseMap.put("st", "サントメ・プリンシペ");
    japaneseMap.put("sv", "エルサルバドル");
    japaneseMap.put("sx", "シント・マールテン島");
    japaneseMap.put("sy", "シリア");
    japaneseMap.put("sz", "エスワティニ");
    japaneseMap.put("tc", "タークス・カイコス諸島");
    japaneseMap.put("td", "チャド");
    japaneseMap.put("tf", "フランス南部と南極の土地");
    japaneseMap.put("tg", "持ち帰り");
    japaneseMap.put("th", "タイ");
    japaneseMap.put("tj", "タジキスタン");
    japaneseMap.put("tk", "トケラウ");
    japaneseMap.put("tl", "東ティモール");
    japaneseMap.put("tm", "トルクメニスタン");
    japaneseMap.put("tn", "チュニジア");
    japaneseMap.put("to", "トンガ");
    japaneseMap.put("tr", "トルキエ");
    japaneseMap.put("tt", "トリニダード・トバゴ");
    japaneseMap.put("tv", "ツバル");
    japaneseMap.put("tw", "台湾");
    japaneseMap.put("tz", "タンザニア");
    japaneseMap.put("ua", "ウクライナ");
    japaneseMap.put("ug", "ウガンダ");
    japaneseMap.put("um", "米国小離島");
    japaneseMap.put("us", "アメリカ合衆国");
    japaneseMap.put("uy", "ウルグアイ");
    japaneseMap.put("uz", "ウズベキスタン");
    japaneseMap.put("va", "バチカン市");
    japaneseMap.put("vc", "セントビンセントおよびグレナディーン諸島");
    japaneseMap.put("ve", "ベネズエラ");
    japaneseMap.put("vg", "イギリス領バージン諸島");
    japaneseMap.put("vi", "アメリカ領ヴァージン諸島");
    japaneseMap.put("vn", "ベトナム");
    japaneseMap.put("vu", "バヌアツ");
    japaneseMap.put("wf", "ウォリス・フツナ");
    japaneseMap.put("ws", "サモア");
    japaneseMap.put("xk", "コソボ");
    japaneseMap.put("ye", "イエメン");
    japaneseMap.put("yt", "マヨット");
    japaneseMap.put("za", "南アフリカ");
    japaneseMap.put("zm", "ザンビア");
    japaneseMap.put("zw", "ジンバブエ");
    japaneseMap.put("ac", "上昇");
    japaneseMap.put("ti", "トリスタン ダ クーニャ");
    japaneseMap.put("bas", "バシコルトスタン");
    japaneseMap.put("bia", "ビキニ環礁");
    japaneseMap.put("bri", "ブルターニュ");
    japaneseMap.put("bur", "ブリヤート");
    japaneseMap.put("cri", "チェチェン・イチケリア共和国");
    japaneseMap.put("che", "チェチェン共和国");
    japaneseMap.put("chu", "チュバシア");
    japaneseMap.put("crm", "クリミア");
    japaneseMap.put("eai", "イースター島");
    japaneseMap.put("dag", "ダゲスタン");
    japaneseMap.put("eu", "欧州連合");
    japaneseMap.put("her", "ヘルム");
    japaneseMap.put("ing", "イングーシ共和国");
    japaneseMap.put("kpr", "クバン人民共和国");
    japaneseMap.put("kab", "カバルダ・バルカリア");
    japaneseMap.put("kal", "カルムイク州");
    japaneseMap.put("kar", "カラチャイ・チェルケシア");
    japaneseMap.put("kkp", "カラカルパクスタン");
    japaneseMap.put("krl", "カレリア");
    japaneseMap.put("kha", "ハカシア");
    japaneseMap.put("kom", "コミ");
    japaneseMap.put("ala", "アラスカ");
  }

  private void loadPortugueseCountries() {
    portugueseMap.put("aa", "Sabá");
    portugueseMap.put("ab", "Abecásia");
    portugueseMap.put("ay", "Adiguésia");
    portugueseMap.put("aj", "Adjária");
    portugueseMap.put("ald", "Alderney");
    portugueseMap.put("alr", "República de Altai");
    portugueseMap.put("ad", "Andorra");
    portugueseMap.put("ae", "Emirados Árabes Unidos");
    portugueseMap.put("af", "Afeganistão");
    portugueseMap.put("ag", "Antígua e Barbuda");
    portugueseMap.put("ai", "Anguila");
    portugueseMap.put("al", "Albânia");
    portugueseMap.put("am", "Armênia");
    portugueseMap.put("ao", "Angola");
    portugueseMap.put("aq", "Antártica");
    portugueseMap.put("an", "Antártica");
    portugueseMap.put("ar", "Argentina");
    portugueseMap.put("as", "Samoa Americana");
    portugueseMap.put("at", "Áustria");
    portugueseMap.put("au", "Austrália");
    portugueseMap.put("aw", "Aruba");
    portugueseMap.put("ax", "Ilhas Aland");
    portugueseMap.put("az", "Azerbaijão");
    portugueseMap.put("ba", "Bósnia e Herzegovina");
    portugueseMap.put("bb", "Barbados");
    portugueseMap.put("bd", "Bangladesh");
    portugueseMap.put("be", "Bélgica");
    portugueseMap.put("bf", "Burkina Faso");
    portugueseMap.put("bg", "Bulgária");
    portugueseMap.put("bh", "Bahrein");
    portugueseMap.put("bi", "Burundi");
    portugueseMap.put("bj", "Benim");
    portugueseMap.put("bl", "São Bartolomeu");
    portugueseMap.put("bm", "Bermudas");
    portugueseMap.put("bn", "Brunei");
    portugueseMap.put("bo", "Bolívia");
    portugueseMap.put("bq", "Holanda caribenha");
    portugueseMap.put("baq", "Antártida Britânica");
    portugueseMap.put("br", "Brasil");
    portugueseMap.put("bs", "Bahamas");
    portugueseMap.put("bt", "Butão");
    portugueseMap.put("bv", "Ilha Bouvet");
    portugueseMap.put("bw", "Botsuana");
    portugueseMap.put("by", "Bielorrússia");
    portugueseMap.put("bz", "Belize");
    portugueseMap.put("ca", "Canadá");
    portugueseMap.put("cc", "Ilhas Cocos");
    portugueseMap.put("cd", "República Democrática do Congo");
    portugueseMap.put("cf", "República Centro-Africana");
    portugueseMap.put("cg", "Congo");
    portugueseMap.put("ch", "Suíça");
    portugueseMap.put("ci", "Costa do Marfim");
    portugueseMap.put("ck", "Ilhas Cook");
    portugueseMap.put("cl", "Chile");
    portugueseMap.put("cm", "Camarões");
    portugueseMap.put("cn", "China");
    portugueseMap.put("co", "Colômbia");
    portugueseMap.put("cr", "Costa Rica");
    portugueseMap.put("cu", "Cuba");
    portugueseMap.put("cv", "cabo Verde");
    portugueseMap.put("cw", "Curaçao");
    portugueseMap.put("cx", "Ilha do Natal");
    portugueseMap.put("cy", "Chipre");
    portugueseMap.put("cz", "República Checa");
    portugueseMap.put("de", "Alemanha");
    portugueseMap.put("dj", "Djibuti");
    portugueseMap.put("dk", "Dinamarca");
    portugueseMap.put("dm", "Domínica");
    portugueseMap.put("do", "República Dominicana");
    portugueseMap.put("dz", "Argélia");
    portugueseMap.put("ec", "Equador");
    portugueseMap.put("ee", "Estônia");
    portugueseMap.put("eg", "Egito");
    portugueseMap.put("eh", "Saara Ocidental");
    portugueseMap.put("ei", "Santo Eustáquio");
    portugueseMap.put("er", "Eritreia");
    portugueseMap.put("es", "Espanha");
    portugueseMap.put("et", "Etiópia");
    portugueseMap.put("fi", "Finlândia");
    portugueseMap.put("fj", "Fiji");
    portugueseMap.put("fk", "Ilhas Malvinas");
    portugueseMap.put("fm", "Micronésia");
    portugueseMap.put("fo", "ilhas Faroe");
    portugueseMap.put("fr", "França");
    portugueseMap.put("ga", "Gabão");
    portugueseMap.put("gb", "Reino Unido");
    portugueseMap.put("gb-eng", "Inglaterra");
    portugueseMap.put("gb-nir", "Irlanda do Norte");
    portugueseMap.put("gb-sct", "Escócia");
    portugueseMap.put("gb-wls", "País de Gales");
    portugueseMap.put("gd", "Granada");
    portugueseMap.put("ge", "Geórgia");
    portugueseMap.put("gf", "Guiana Francesa");
    portugueseMap.put("gg", "Guernsey");
    portugueseMap.put("gh", "Gana");
    portugueseMap.put("gi", "Gibraltar");
    portugueseMap.put("gl", "Groenlândia");
    portugueseMap.put("gm", "Gâmbia");
    portugueseMap.put("gn", "Guiné");
    portugueseMap.put("gp", "Guadalupe");
    portugueseMap.put("gq", "Guiné Equatorial");
    portugueseMap.put("gr", "Grécia");
    portugueseMap.put("gs", "Geórgia do Sul e Ilhas Sandwich do Sul");
    portugueseMap.put("gt", "Guatemala");
    portugueseMap.put("gu", "Guam");
    portugueseMap.put("gw", "Guiné-Bissau");
    portugueseMap.put("gy", "Guiana");
    portugueseMap.put("hk", "Hong Kong");
    portugueseMap.put("hm", "Ilha Heard e Ilhas McDonald");
    portugueseMap.put("hn", "Honduras");
    portugueseMap.put("hr", "Croácia");
    portugueseMap.put("ht", "Haiti");
    portugueseMap.put("hu", "Hungria");
    portugueseMap.put("id", "Indonésia");
    portugueseMap.put("ie", "Irlanda");
    portugueseMap.put("il", "Israel");
    portugueseMap.put("im", "Ilha de Man");
    portugueseMap.put("in", "Índia");
    portugueseMap.put("io", "Território Britânico do Oceano Índico");
    portugueseMap.put("iq", "Iraque");
    portugueseMap.put("ir", "Irã");
    portugueseMap.put("is", "Islândia");
    portugueseMap.put("it", "Itália");
    portugueseMap.put("je", "Jersey");
    portugueseMap.put("jm", "Jamaica");
    portugueseMap.put("jo", "Jordânia");
    portugueseMap.put("jp", "Japão");
    portugueseMap.put("ke", "Quênia");
    portugueseMap.put("kg", "Quirguistão");
    portugueseMap.put("kh", "Camboja");
    portugueseMap.put("ki", "Quiribáti");
    portugueseMap.put("km", "Comores");
    portugueseMap.put("kn", "São Cristóvão e Nevis");
    portugueseMap.put("kp", "Coréia do Norte");
    portugueseMap.put("kr", "Coreia do Sul");
    portugueseMap.put("kw", "Kuwait");
    portugueseMap.put("ky", "Ilhas Cayman");
    portugueseMap.put("kz", "Cazaquistão");
    portugueseMap.put("la", "Laos");
    portugueseMap.put("lb", "Líbano");
    portugueseMap.put("lc", "Santa Lúcia");
    portugueseMap.put("li", "Liechtenstein");
    portugueseMap.put("lk", "Sri Lanka");
    portugueseMap.put("lr", "Libéria");
    portugueseMap.put("ls", "Lesoto");
    portugueseMap.put("lt", "Lituânia");
    portugueseMap.put("lu", "Luxemburgo");
    portugueseMap.put("lv", "Letônia");
    portugueseMap.put("ly", "Líbia");
    portugueseMap.put("ma", "Marrocos");
    portugueseMap.put("mc", "Mônaco");
    portugueseMap.put("md", "Moldávia");
    portugueseMap.put("me", "Montenegro");
    portugueseMap.put("mf", "são Martinho");
    portugueseMap.put("mg", "Madagáscar");
    portugueseMap.put("mh", "Ilhas Marshall");
    portugueseMap.put("mk", "Macedônia do Norte");
    portugueseMap.put("ml", "Mali");
    portugueseMap.put("mm", "Mianmar");
    portugueseMap.put("mn", "Mongólia");
    portugueseMap.put("mo", "Macau");
    portugueseMap.put("mp", "Ilhas Marianas do Norte");
    portugueseMap.put("mq", "Martinica");
    portugueseMap.put("mi", "Martinica");
    portugueseMap.put("mr", "Mauritânia");
    portugueseMap.put("ms", "Montserrate");
    portugueseMap.put("mt", "Malta");
    portugueseMap.put("mu", "Maurício");
    portugueseMap.put("mv", "Maldivas");
    portugueseMap.put("mw", "Maláui");
    portugueseMap.put("mx", "México");
    portugueseMap.put("my", "Malásia");
    portugueseMap.put("mz", "Moçambique");
    portugueseMap.put("na", "Namíbia");
    portugueseMap.put("nc", "Nova Caledônia");
    portugueseMap.put("ne", "Níger");
    portugueseMap.put("nf", "Ilha Norfolk");
    portugueseMap.put("ng", "Nigéria");
    portugueseMap.put("ni", "Nicarágua");
    portugueseMap.put("nl", "Holanda");
    portugueseMap.put("no", "Noruega");
    portugueseMap.put("np", "Nepal");
    portugueseMap.put("nr", "Nauru");
    portugueseMap.put("nu", "Niue");
    portugueseMap.put("nz", "Nova Zelândia");
    portugueseMap.put("om", "Omã");
    portugueseMap.put("pa", "Panamá");
    portugueseMap.put("pe", "Peru");
    portugueseMap.put("pf", "Polinésia Francesa");
    portugueseMap.put("pg", "Papua Nova Guiné");
    portugueseMap.put("ph", "Filipinas");
    portugueseMap.put("pk", "Paquistão");
    portugueseMap.put("pl", "Polônia");
    portugueseMap.put("pm", "São Pedro e Miquelon");
    portugueseMap.put("pn", "Ilhas Pitcairn");
    portugueseMap.put("pr", "Porto Rico");
    portugueseMap.put("ps", "Palestina");
    portugueseMap.put("pt", "Portugal");
    portugueseMap.put("pw", "Palau");
    portugueseMap.put("py", "Paraguai");
    portugueseMap.put("qa", "Catar");
    portugueseMap.put("re", "Reunião");
    portugueseMap.put("ro", "Romênia");
    portugueseMap.put("rs", "Sérvia");
    portugueseMap.put("ru", "Rússia");
    portugueseMap.put("rw", "Ruanda");
    portugueseMap.put("sa", "Arábia Saudita");
    portugueseMap.put("sb", "Ilhas Salomão");
    portugueseMap.put("sc", "Seicheles");
    portugueseMap.put("sd", "Sudão");
    portugueseMap.put("se", "Suécia");
    portugueseMap.put("sg", "Cingapura");
    portugueseMap.put("sh", "Santa Helena");
    portugueseMap.put("si", "Eslovênia");
    portugueseMap.put("sj", "Svalbard e Jan Mayen");
    portugueseMap.put("sk", "Eslováquia");
    portugueseMap.put("sl", "Serra Leoa");
    portugueseMap.put("sm", "São Marino");
    portugueseMap.put("sn", "Senegal");
    portugueseMap.put("so", "Somália");
    portugueseMap.put("sr", "Suriname");
    portugueseMap.put("ss", "Sudão do Sul");
    portugueseMap.put("st", "São Tomé e Príncipe");
    portugueseMap.put("sv", "El Salvador");
    portugueseMap.put("sx", "São Martinho");
    portugueseMap.put("sy", "Síria");
    portugueseMap.put("sz", "Essuatíni");
    portugueseMap.put("tc", "Ilhas Turcas e Caicos");
    portugueseMap.put("td", "Chade");
    portugueseMap.put("tf", "Terras Austrais e Antárticas Francesas");
    portugueseMap.put("tg", "Togo");
    portugueseMap.put("th", "Tailândia");
    portugueseMap.put("tj", "Tadjiquistão");
    portugueseMap.put("tk", "Toquelau");
    portugueseMap.put("tl", "Timor-Leste");
    portugueseMap.put("tm", "Turcomenistão");
    portugueseMap.put("tn", "Tunísia");
    portugueseMap.put("to", "Tonga");
    portugueseMap.put("tr", "Turquia");
    portugueseMap.put("tt", "Trinidad e Tobago");
    portugueseMap.put("tv", "Tuvalu");
    portugueseMap.put("tw", "Taiwan");
    portugueseMap.put("tz", "Tanzânia");
    portugueseMap.put("ua", "Ucrânia");
    portugueseMap.put("ug", "Uganda");
    portugueseMap.put("um", "Ilhas Menores Distantes dos Estados Unidos");
    portugueseMap.put("us", "Estados Unidos da América");
    portugueseMap.put("uy", "Uruguai");
    portugueseMap.put("uz", "Uzbequistão");
    portugueseMap.put("va", "Cidade do Vaticano");
    portugueseMap.put("vc", "São Vicente e Granadinas");
    portugueseMap.put("ve", "Venezuela");
    portugueseMap.put("vg", "Ilhas Virgens Britânicas");
    portugueseMap.put("vi", "Ilhas Virgens Americanas");
    portugueseMap.put("vn", "Vietnã");
    portugueseMap.put("vu", "Vanuatu");
    portugueseMap.put("wf", "Wallis e Futuna");
    portugueseMap.put("ws", "Samoa");
    portugueseMap.put("xk", "Kosovo");
    portugueseMap.put("ye", "Iémen");
    portugueseMap.put("yt", "Maiote");
    portugueseMap.put("za", "África do Sul");
    portugueseMap.put("zm", "Zâmbia");
    portugueseMap.put("zw", "Zimbábue");
    portugueseMap.put("ac", "Ascensão");
    portugueseMap.put("ti", "Tristão da Cunha");
    portugueseMap.put("bas", "Bascortostão");
    portugueseMap.put("bia", "Atol do Biquíni");
    portugueseMap.put("bri", "Bretanha");
    portugueseMap.put("bur", "Buryatia");
    portugueseMap.put("cri", "República Chechena da Ichkeria");
    portugueseMap.put("che", "República da Chechênia");
    portugueseMap.put("chu", "Chuvashia");
    portugueseMap.put("crm", "Crimeia");
    portugueseMap.put("eai", "Ilha de Páscoa");
    portugueseMap.put("dag", "Daguestão");
    portugueseMap.put("eu", "União Europeia");
    portugueseMap.put("her", "Herm");
    portugueseMap.put("ing", "Inguchétia");
    portugueseMap.put("kpr", "República Popular de Kuban");
    portugueseMap.put("kab", "Cabardino-Balcária");
    portugueseMap.put("kal", "Calmúquia");
    portugueseMap.put("kar", "Karachai-Cherkessia");
    portugueseMap.put("kkp", "Caracalpaquistão");
    portugueseMap.put("krl", "Carélia");
    portugueseMap.put("kha", "Cacássia");
    portugueseMap.put("kom", "Komi");
    portugueseMap.put("ala", "Alasca");
  }

  private void loadSpanishCountries() {
    spanishMap.put("aa", "Sabá");
    spanishMap.put("ab", "Abjasia");
    spanishMap.put("ay", "Adygea");
    spanishMap.put("aj", "Adjara");
    spanishMap.put("ald", "alderney");
    spanishMap.put("alr", "República de Altái");
    spanishMap.put("ad", "Andorra");
    spanishMap.put("ae", "Emiratos Árabes Unidos");
    spanishMap.put("af", "Afganistán");
    spanishMap.put("ag", "Antigua y Barbuda");
    spanishMap.put("ai", "Anguila");
    spanishMap.put("al", "Albania");
    spanishMap.put("am", "Armenia");
    spanishMap.put("ao", "Angola");
    spanishMap.put("aq", "Antártida");
    spanishMap.put("an", "Antártida");
    spanishMap.put("ar", "Argentina");
    spanishMap.put("as", "Samoa Americana");
    spanishMap.put("at", "Austria");
    spanishMap.put("au", "Australia");
    spanishMap.put("aw", "Aruba");
    spanishMap.put("ax", "Islas Aland");
    spanishMap.put("az", "Azerbaiyán");
    spanishMap.put("ba", "Bosnia y Herzegovina");
    spanishMap.put("bb", "Barbados");
    spanishMap.put("bd", "Bangladesh");
    spanishMap.put("be", "Bélgica");
    spanishMap.put("bf", "Burkina Faso");
    spanishMap.put("bg", "Bulgaria");
    spanishMap.put("bh", "Bahréin");
    spanishMap.put("bi", "Burundi");
    spanishMap.put("bj", "Benín");
    spanishMap.put("bl", "San Bartolomé");
    spanishMap.put("bm", "Islas Bermudas");
    spanishMap.put("bn", "Brunéi");
    spanishMap.put("bo", "bolivia");
    spanishMap.put("bq", "Caribe Neerlandés");
    spanishMap.put("baq", "Antártida británica");
    spanishMap.put("br", "Brasil");
    spanishMap.put("bs", "bahamas");
    spanishMap.put("bt", "Bután");
    spanishMap.put("bv", "Isla Bouvet");
    spanishMap.put("bw", "Botsuana");
    spanishMap.put("by", "Bielorrusia");
    spanishMap.put("bz", "Belice");
    spanishMap.put("ca", "Canadá");
    spanishMap.put("cc", "Islas Cocos");
    spanishMap.put("cd", "República Democrática del Congo");
    spanishMap.put("cf", "República Centroafricana");
    spanishMap.put("cg", "Congo");
    spanishMap.put("ch", "Suiza");
    spanishMap.put("ci", "Costa de Marfil");
    spanishMap.put("ck", "Islas Cook");
    spanishMap.put("cl", "Chile");
    spanishMap.put("cm", "Camerún");
    spanishMap.put("cn", "Porcelana");
    spanishMap.put("co", "Colombia");
    spanishMap.put("cr", "Costa Rica");
    spanishMap.put("cu", "Cuba");
    spanishMap.put("cv", "Cabo Verde");
    spanishMap.put("cw", "Curazao");
    spanishMap.put("cx", "Isla de Navidad");
    spanishMap.put("cy", "Chipre");
    spanishMap.put("cz", "República Checa");
    spanishMap.put("de", "Alemania");
    spanishMap.put("dj", "Yibuti");
    spanishMap.put("dk", "Dinamarca");
    spanishMap.put("dm", "Dominica");
    spanishMap.put("do", "República Dominicana");
    spanishMap.put("dz", "Argelia");
    spanishMap.put("ec", "Ecuador");
    spanishMap.put("ee", "Estonia");
    spanishMap.put("eg", "Egipto");
    spanishMap.put("eh", "Sahara Occidental");
    spanishMap.put("ei", "San Eustaquio");
    spanishMap.put("er", "Eritrea");
    spanishMap.put("es", "España");
    spanishMap.put("et", "Etiopía");
    spanishMap.put("fi", "Finlandia");
    spanishMap.put("fj", "Fiyi");
    spanishMap.put("fk", "Islas Malvinas");
    spanishMap.put("fm", "Micronesia");
    spanishMap.put("fo", "Islas Faroe");
    spanishMap.put("fr", "Francia");
    spanishMap.put("ga", "Gabón");
    spanishMap.put("gb", "Reino Unido");
    spanishMap.put("gb-eng", "Inglaterra");
    spanishMap.put("gb-nir", "Irlanda del Norte");
    spanishMap.put("gb-sct", "Escocia");
    spanishMap.put("gb-wls", "Gales");
    spanishMap.put("gd", "Granada");
    spanishMap.put("ge", "Georgia");
    spanishMap.put("gf", "Guayana Francesa");
    spanishMap.put("gg", "Guernesey");
    spanishMap.put("gh", "Ghana");
    spanishMap.put("gi", "Gibraltar");
    spanishMap.put("gl", "Groenlandia");
    spanishMap.put("gm", "Gambia");
    spanishMap.put("gn", "Guinea");
    spanishMap.put("gp", "Guadalupe");
    spanishMap.put("gq", "Guinea Ecuatorial");
    spanishMap.put("gr", "Grecia");
    spanishMap.put("gs", "Georgia del sur y las islas Sandwich del sur");
    spanishMap.put("gt", "Guatemala");
    spanishMap.put("gu", "Guam");
    spanishMap.put("gw", "Guinea-Bisáu");
    spanishMap.put("gy", "Guayana");
    spanishMap.put("hk", "Hong Kong");
    spanishMap.put("hm", "Islas Heard y McDonald");
    spanishMap.put("hn", "Honduras");
    spanishMap.put("hr", "Croacia");
    spanishMap.put("ht", "Haití");
    spanishMap.put("hu", "Hungría");
    spanishMap.put("id", "Indonesia");
    spanishMap.put("ie", "Irlanda");
    spanishMap.put("il", "Israel");
    spanishMap.put("im", "Isla del hombre");
    spanishMap.put("in", "India");
    spanishMap.put("io", "Territorio Británico del Océano Índico");
    spanishMap.put("iq", "Irak");
    spanishMap.put("ir", "Irán");
    spanishMap.put("is", "Islandia");
    spanishMap.put("it", "Italia");
    spanishMap.put("je", "Jersey");
    spanishMap.put("jm", "Jamaica");
    spanishMap.put("jo", "Jordán");
    spanishMap.put("jp", "Japón");
    spanishMap.put("ke", "Kenia");
    spanishMap.put("kg", "Kirguistán");
    spanishMap.put("kh", "Camboya");
    spanishMap.put("ki", "Kiribati");
    spanishMap.put("km", "Comoras");
    spanishMap.put("kn", "San Cristóbal y Nieves");
    spanishMap.put("kp", "Corea del Norte");
    spanishMap.put("kr", "Corea del Sur");
    spanishMap.put("kw", "Kuwait");
    spanishMap.put("ky", "Islas Caimán");
    spanishMap.put("kz", "Kazajstán");
    spanishMap.put("la", "Laos");
    spanishMap.put("lb", "Líbano");
    spanishMap.put("lc", "Santa Lucía");
    spanishMap.put("li", "Liechtenstein");
    spanishMap.put("lk", "Sri Lanka");
    spanishMap.put("lr", "Liberia");
    spanishMap.put("ls", "Lesoto");
    spanishMap.put("lt", "Lituania");
    spanishMap.put("lu", "Luxemburgo");
    spanishMap.put("lv", "Letonia");
    spanishMap.put("ly", "Libia");
    spanishMap.put("ma", "Marruecos");
    spanishMap.put("mc", "Mónaco");
    spanishMap.put("md", "Moldavia");
    spanishMap.put("me", "Montenegro");
    spanishMap.put("mf", "San Martín");
    spanishMap.put("mg", "Madagascar");
    spanishMap.put("mh", "Islas Marshall");
    spanishMap.put("mk", "Macedonia del Norte");
    spanishMap.put("ml", "Malí");
    spanishMap.put("mm", "Birmania");
    spanishMap.put("mn", "Mongolia");
    spanishMap.put("mo", "Macao");
    spanishMap.put("mp", "Islas Marianas del Norte");
    spanishMap.put("mq", "Martinica");
    spanishMap.put("mi", "Martinica");
    spanishMap.put("mr", "Mauritania");
    spanishMap.put("ms", "Montserrat");
    spanishMap.put("mt", "Malta");
    spanishMap.put("mu", "Mauricio");
    spanishMap.put("mv", "Maldivas");
    spanishMap.put("mw", "Malaui");
    spanishMap.put("mx", "México");
    spanishMap.put("my", "Malasia");
    spanishMap.put("mz", "Mozambique");
    spanishMap.put("na", "Namibia");
    spanishMap.put("nc", "Nueva Caledonia");
    spanishMap.put("ne", "Níger");
    spanishMap.put("nf", "Isla Norfolk");
    spanishMap.put("ng", "Nigeria");
    spanishMap.put("ni", "Nicaragua");
    spanishMap.put("nl", "Países Bajos");
    spanishMap.put("no", "Noruega");
    spanishMap.put("np", "Nepal");
    spanishMap.put("nr", "Nauru");
    spanishMap.put("nu", "Niue");
    spanishMap.put("nz", "Nueva Zelanda");
    spanishMap.put("om", "Omán");
    spanishMap.put("pa", "Panamá");
    spanishMap.put("pe", "Perú");
    spanishMap.put("pf", "Polinesia francés");
    spanishMap.put("pg", "Papúa Nueva Guinea");
    spanishMap.put("ph", "Filipinas");
    spanishMap.put("pk", "Pakistán");
    spanishMap.put("pl", "Polonia");
    spanishMap.put("pm", "San Pedro y Miquelón");
    spanishMap.put("pn", "Islas Pitcairn");
    spanishMap.put("pr", "Puerto Rico");
    spanishMap.put("ps", "Palestina");
    spanishMap.put("pt", "Portugal");
    spanishMap.put("pw", "Palaos");
    spanishMap.put("py", "Paraguay");
    spanishMap.put("qa", "Katar");
    spanishMap.put("re", "Reunión");
    spanishMap.put("ro", "Rumania");
    spanishMap.put("rs", "Serbia");
    spanishMap.put("ru", "Rusia");
    spanishMap.put("rw", "Ruanda");
    spanishMap.put("sa", "Arabia Saudita");
    spanishMap.put("sb", "Islas Salomón");
    spanishMap.put("sc", "Seychelles");
    spanishMap.put("sd", "Sudán");
    spanishMap.put("se", "Suecia");
    spanishMap.put("sg", "Singapur");
    spanishMap.put("sh", "santa elena");
    spanishMap.put("si", "Eslovenia");
    spanishMap.put("sj", "Svalbard y Jan Mayen");
    spanishMap.put("sk", "Eslovaquia");
    spanishMap.put("sl", "Sierra Leona");
    spanishMap.put("sm", "San Marino");
    spanishMap.put("sn", "Senegal");
    spanishMap.put("so", "Somalia");
    spanishMap.put("sr", "Surinam");
    spanishMap.put("ss", "Sudán del Sur");
    spanishMap.put("st", "Santo Tomé y Príncipe");
    spanishMap.put("sv", "El Salvador");
    spanishMap.put("sx", "San Martín");
    spanishMap.put("sy", "Siria");
    spanishMap.put("sz", "Esuatini");
    spanishMap.put("tc", "Islas Turcas y Caicos");
    spanishMap.put("td", "Chad");
    spanishMap.put("tf", "Tierras Australes y Antárticas Francesas");
    spanishMap.put("tg", "Ir");
    spanishMap.put("th", "Tailandia");
    spanishMap.put("tj", "Tayikistán");
    spanishMap.put("tk", "Tokelau");
    spanishMap.put("tl", "Timor Oriental");
    spanishMap.put("tm", "Turkmenistán");
    spanishMap.put("tn", "Túnez");
    spanishMap.put("to", "Tonga");
    spanishMap.put("tr", "Turquía");
    spanishMap.put("tt", "Trinidad y Tobago");
    spanishMap.put("tv", "Tuvalu");
    spanishMap.put("tw", "Taiwán");
    spanishMap.put("tz", "Tanzania");
    spanishMap.put("ua", "Ucrania");
    spanishMap.put("ug", "Uganda");
    spanishMap.put("um", "Islas menores alejadas de los Estados Unidos");
    spanishMap.put("us", "Estados Unidos de América");
    spanishMap.put("uy", "Uruguay");
    spanishMap.put("uz", "Uzbekistán");
    spanishMap.put("va", "Ciudad del Vaticano");
    spanishMap.put("vc", "San Vicente y las Granadinas");
    spanishMap.put("ve", "Venezuela");
    spanishMap.put("vg", "Islas Vírgenes Británicas");
    spanishMap.put("vi", "Islas Vírgenes US");
    spanishMap.put("vn", "Vietnam");
    spanishMap.put("vu", "Vanuatu");
    spanishMap.put("wf", "Wallis y Futuna");
    spanishMap.put("ws", "Samoa");
    spanishMap.put("xk", "Kosovo");
    spanishMap.put("ye", "Yemen");
    spanishMap.put("yt", "Mayotte");
    spanishMap.put("za", "Sudáfrica");
    spanishMap.put("zm", "Zambia");
    spanishMap.put("zw", "Zimbabue");
    spanishMap.put("ac", "Ascensión");
    spanishMap.put("ti", "Tristán da Cunha");
    spanishMap.put("bas", "Bashkortostán");
    spanishMap.put("bia", "Atolón de Bikini");
    spanishMap.put("bri", "Bretaña");
    spanishMap.put("bur", "Buriatia");
    spanishMap.put("cri", "República Chechena de Ichkeria");
    spanishMap.put("che", "República de Chechenia");
    spanishMap.put("chu", "Chuvashia");
    spanishMap.put("crm", "Crimea");
    spanishMap.put("eai", "Isla de Pascua");
    spanishMap.put("dag", "Daguestán");
    spanishMap.put("eu", "Unión Europea");
    spanishMap.put("her", "Herm");
    spanishMap.put("ing", "Ingusetia");
    spanishMap.put("kpr", "República Popular de Kubán");
    spanishMap.put("kab", "Kabardia-Balkaria");
    spanishMap.put("kal", "Kalmukia");
    spanishMap.put("kar", "Karachay-Cherkessia");
    spanishMap.put("kkp", "Karakalpakstán");
    spanishMap.put("krl", "Carelia");
    spanishMap.put("kha", "Jakasia");
    spanishMap.put("kom", "komi");
    spanishMap.put("ala", "Alaska");
  }

  private void loadArabicCountries() {
    arabicMap.put("aa", "سابا");
    arabicMap.put("ab", "أبخازيا");
    arabicMap.put("ay", "أديغيا");
    arabicMap.put("aj", "أدجارا");
    arabicMap.put("ald", "ألديرني");
    arabicMap.put("alr", "جمهورية التاي");
    arabicMap.put("ad", "أندورا");
    arabicMap.put("ae", "الإمارات العربية المتحدة");
    arabicMap.put("af", "أفغانستان");
    arabicMap.put("ag", "أنتيغوا وبربودا");
    arabicMap.put("ai", "أنغيلا");
    arabicMap.put("al", "ألبانيا");
    arabicMap.put("am", "أرمينيا");
    arabicMap.put("ao", "أنغولا");
    arabicMap.put("aq", "القارة القطبية الجنوبية");
    arabicMap.put("an", "القارة القطبية الجنوبية");
    arabicMap.put("ar", "الأرجنتين");
    arabicMap.put("as", "ساموا الأمريكية");
    arabicMap.put("at", "النمسا");
    arabicMap.put("au", "أستراليا");
    arabicMap.put("aw", "أروبا");
    arabicMap.put("ax", "جزر آلاند");
    arabicMap.put("az", "أذربيجان");
    arabicMap.put("ba", "البوسنة والهرسك");
    arabicMap.put("bb", "بربادوس");
    arabicMap.put("bd", "بنغلاديش");
    arabicMap.put("be", "بلجيكا");
    arabicMap.put("bf", "بوركينا فاسو");
    arabicMap.put("bg", "بلغاريا");
    arabicMap.put("bh", "البحرين");
    arabicMap.put("bi", "بوروندي");
    arabicMap.put("bj", "بنين");
    arabicMap.put("bl", "سانت بارتيليمي");
    arabicMap.put("bm", "برمودا");
    arabicMap.put("bn", "بروناي");
    arabicMap.put("bo", "بوليفيا");
    arabicMap.put("bq", "هولندا الكاريبية");
    arabicMap.put("baq", "القطب الجنوبي البريطاني");
    arabicMap.put("br", "البرازيل");
    arabicMap.put("bs", "جزر البهاما");
    arabicMap.put("bt", "بوتان");
    arabicMap.put("bv", "جزيرة بوفيه");
    arabicMap.put("bw", "بوتسوانا");
    arabicMap.put("by", "بيلاروسيا");
    arabicMap.put("bz", "بليز");
    arabicMap.put("ca", "كندا");
    arabicMap.put("cc", "جزر كوكوس");
    arabicMap.put("cd", "جمهورية الكونغو الديموقراطية");
    arabicMap.put("cf", "جمهورية افريقيا الوسطى");
    arabicMap.put("cg", "الكونغو");
    arabicMap.put("ch", "سويسرا");
    arabicMap.put("ci", "ساحل العاج");
    arabicMap.put("ck", "جزر كوك");
    arabicMap.put("cl", "شيلي");
    arabicMap.put("cm", "الكاميرون");
    arabicMap.put("cn", "الصين");
    arabicMap.put("co", "كولومبيا");
    arabicMap.put("cr", "كوستا ريكا");
    arabicMap.put("cu", "كوبا");
    arabicMap.put("cv", "الرأس الأخضر");
    arabicMap.put("cw", "كوراكاو");
    arabicMap.put("cx", "جزيرة عيد الميلاد");
    arabicMap.put("cy", "قبرص");
    arabicMap.put("cz", "الجمهورية التشيكية");
    arabicMap.put("de", "ألمانيا");
    arabicMap.put("dj", "جيبوتي");
    arabicMap.put("dk", "الدنمارك");
    arabicMap.put("dm", "دومينيكا");
    arabicMap.put("do", "جمهورية الدومينيكان");
    arabicMap.put("dz", "الجزائر");
    arabicMap.put("ec", "الاكوادور");
    arabicMap.put("ee", "إستونيا");
    arabicMap.put("eg", "مصر");
    arabicMap.put("eh", "الصحراء الغربية");
    arabicMap.put("ei", "سينت اوستاتيوس");
    arabicMap.put("er", "إريتريا");
    arabicMap.put("es", "إسبانيا");
    arabicMap.put("et", "أثيوبيا");
    arabicMap.put("fi", "فنلندا");
    arabicMap.put("fj", "فيجي");
    arabicMap.put("fk", "جزر فوكلاند");
    arabicMap.put("fm", "ميكرونيزيا");
    arabicMap.put("fo", "جزر فاروس");
    arabicMap.put("fr", "فرنسا");
    arabicMap.put("ga", "الجابون");
    arabicMap.put("gb", "المملكة المتحدة");
    arabicMap.put("gb-eng", "إنكلترا");
    arabicMap.put("gb-nir", "إيرلندا الشمالية");
    arabicMap.put("gb-sct", "اسكتلندا");
    arabicMap.put("gb-wls", "ويلز");
    arabicMap.put("gd", "غرينادا");
    arabicMap.put("ge", "جورجيا");
    arabicMap.put("gf", "غيانا الفرنسية");
    arabicMap.put("gg", "غيرنسي");
    arabicMap.put("gh", "غانا");
    arabicMap.put("gi", "جبل طارق");
    arabicMap.put("gl", "الأرض الخضراء");
    arabicMap.put("gm", "غامبيا");
    arabicMap.put("gn", "غينيا");
    arabicMap.put("gp", "جوادلوب");
    arabicMap.put("gq", "غينيا الإستوائية");
    arabicMap.put("gr", "اليونان");
    arabicMap.put("gs", "جورجيا الجنوبية وجزر ساندويتش الجنوبية");
    arabicMap.put("gt", "غواتيمالا");
    arabicMap.put("gu", "غوام");
    arabicMap.put("gw", "غينيا بيساو");
    arabicMap.put("gy", "غيانا");
    arabicMap.put("hk", "هونج كونج");
    arabicMap.put("hm", "قلب الجزيرة وجزر ماكدونالز");
    arabicMap.put("hn", "هندوراس");
    arabicMap.put("hr", "كرواتيا");
    arabicMap.put("ht", "هايتي");
    arabicMap.put("hu", "هنغاريا");
    arabicMap.put("id", "إندونيسيا");
    arabicMap.put("ie", "أيرلندا");
    arabicMap.put("il", "إسرائيل");
    arabicMap.put("im", "جزيرة آيل أوف مان");
    arabicMap.put("in", "الهند");
    arabicMap.put("io", "إقليم المحيط البريطاني الهندي");
    arabicMap.put("iq", "العراق");
    arabicMap.put("ir", "إيران");
    arabicMap.put("is", "أيسلندا");
    arabicMap.put("it", "إيطاليا");
    arabicMap.put("je", "جيرسي");
    arabicMap.put("jm", "جامايكا");
    arabicMap.put("jo", "الأردن");
    arabicMap.put("jp", "اليابان");
    arabicMap.put("ke", "كينيا");
    arabicMap.put("kg", "قيرغيزستان");
    arabicMap.put("kh", "كمبوديا");
    arabicMap.put("ki", "كيريباتي");
    arabicMap.put("km", "جزر القمر");
    arabicMap.put("kn", "سانت كيتس ونيفيس");
    arabicMap.put("kp", "كوريا الشمالية");
    arabicMap.put("kr", "كوريا الجنوبية");
    arabicMap.put("kw", "الكويت");
    arabicMap.put("ky", "جزر كايمان");
    arabicMap.put("kz", "كازاخستان");
    arabicMap.put("la", "لاوس");
    arabicMap.put("lb", "لبنان");
    arabicMap.put("lc", "القديسة لوسيا");
    arabicMap.put("li", "ليختنشتاين");
    arabicMap.put("lk", "سيريلانكا");
    arabicMap.put("lr", "ليبيريا");
    arabicMap.put("ls", "ليسوتو");
    arabicMap.put("lt", "ليتوانيا");
    arabicMap.put("lu", "لوكسمبورغ");
    arabicMap.put("lv", "لاتفيا");
    arabicMap.put("ly", "ليبيا");
    arabicMap.put("ma", "المغرب");
    arabicMap.put("mc", "موناكو");
    arabicMap.put("md", "مولدوفا");
    arabicMap.put("me", "الجبل الأسود");
    arabicMap.put("mf", "القديس مارتن");
    arabicMap.put("mg", "مدغشقر");
    arabicMap.put("mh", "جزر مارشال");
    arabicMap.put("mk", "مقدونيا الشمالية");
    arabicMap.put("ml", "مالي");
    arabicMap.put("mm", "ميانمار");
    arabicMap.put("mn", "منغوليا");
    arabicMap.put("mo", "ماكاو");
    arabicMap.put("mp", "جزر مريانا الشمالية");
    arabicMap.put("mq", "مارتينيك");
    arabicMap.put("mi", "مارتينيك");
    arabicMap.put("mr", "موريتانيا");
    arabicMap.put("ms", "مونتسيرات");
    arabicMap.put("mt", "مالطا");
    arabicMap.put("mu", "موريشيوس");
    arabicMap.put("mv", "جزر المالديف");
    arabicMap.put("mw", "ملاوي");
    arabicMap.put("mx", "المكسيك");
    arabicMap.put("my", "ماليزيا");
    arabicMap.put("mz", "موزمبيق");
    arabicMap.put("na", "ناميبيا");
    arabicMap.put("nc", "كاليدونيا الجديدة");
    arabicMap.put("ne", "النيجر");
    arabicMap.put("nf", "جزيرة نورفولك");
    arabicMap.put("ng", "نيجيريا");
    arabicMap.put("ni", "نيكاراغوا");
    arabicMap.put("nl", "هولندا");
    arabicMap.put("no", "النرويج");
    arabicMap.put("np", "نيبال");
    arabicMap.put("nr", "ناورو");
    arabicMap.put("nu", "نيوي");
    arabicMap.put("nz", "نيوزيلندا");
    arabicMap.put("om", "سلطنة عمان");
    arabicMap.put("pa", "بنما");
    arabicMap.put("pe", "بيرو");
    arabicMap.put("pf", "بولينيزيا الفرنسية");
    arabicMap.put("pg", "بابوا غينيا الجديدة");
    arabicMap.put("ph", "فيلبيني");
    arabicMap.put("pk", "باكستان");
    arabicMap.put("pl", "بولندا");
    arabicMap.put("pm", "سانت بيير وميكلون");
    arabicMap.put("pn", "جزر بيتكيرن");
    arabicMap.put("pr", "بورتوريكو");
    arabicMap.put("ps", "فلسطين");
    arabicMap.put("pt", "البرتغال");
    arabicMap.put("pw", "بالاو");
    arabicMap.put("py", "باراجواي");
    arabicMap.put("qa", "دولة قطر");
    arabicMap.put("re", "جمع شمل");
    arabicMap.put("ro", "رومانيا");
    arabicMap.put("rs", "صربيا");
    arabicMap.put("ru", "روسيا");
    arabicMap.put("rw", "رواندا");
    arabicMap.put("sa", "المملكة العربية السعودية");
    arabicMap.put("sb", "جزر سليمان");
    arabicMap.put("sc", "سيشيل");
    arabicMap.put("sd", "السودان");
    arabicMap.put("se", "السويد");
    arabicMap.put("sg", "سنغافورة");
    arabicMap.put("sh", "سانت هيلانة");
    arabicMap.put("si", "سلوفينيا");
    arabicMap.put("sj", "سفالبارد وجان ماين");
    arabicMap.put("sk", "سلوفاكيا");
    arabicMap.put("sl", "سيرا ليون");
    arabicMap.put("sm", "سان مارينو");
    arabicMap.put("sn", "السنغال");
    arabicMap.put("so", "الصومال");
    arabicMap.put("sr", "سورينام");
    arabicMap.put("ss", "جنوب السودان");
    arabicMap.put("st", "سان تومي وبرينسيبي");
    arabicMap.put("sv", "السلفادور");
    arabicMap.put("sx", "سينت مارتن");
    arabicMap.put("sy", "سوريا");
    arabicMap.put("sz", "إيسواتيني");
    arabicMap.put("tc", "جزر تركس وكايكوس");
    arabicMap.put("td", "تشاد");
    arabicMap.put("tf", "الأراضي الفرنسية الجنوبية والقطبية الجنوبية");
    arabicMap.put("tg", "توجو");
    arabicMap.put("th", "تايلاند");
    arabicMap.put("tj", "طاجيكستان");
    arabicMap.put("tk", "توكيلاو");
    arabicMap.put("tl", "تيمور الشرقية");
    arabicMap.put("tm", "تركمانستان");
    arabicMap.put("tn", "تونس");
    arabicMap.put("to", "تونغا");
    arabicMap.put("tr", "تركيا");
    arabicMap.put("tt", "ترينداد وتوباغو");
    arabicMap.put("tv", "توفالو");
    arabicMap.put("tw", "تايوان");
    arabicMap.put("tz", "تنزانيا");
    arabicMap.put("ua", "أوكرانيا");
    arabicMap.put("ug", "أوغندا");
    arabicMap.put("um", "جزر الولايات المتحدة البعيدة الصغرى");
    arabicMap.put("us", "الولايات المتحدة الأمريكية");
    arabicMap.put("uy", "أوروغواي");
    arabicMap.put("uz", "أوزبكستان");
    arabicMap.put("va", "مدينة الفاتيكان");
    arabicMap.put("vc", "سانت فنسنت وجزر غرينادين");
    arabicMap.put("ve", "فنزويلا");
    arabicMap.put("vg", "جزر فيرجن البريطانية");
    arabicMap.put("vi", "جزر فيرجن الأمريكية");
    arabicMap.put("vn", "فيتنام");
    arabicMap.put("vu", "فانواتو");
    arabicMap.put("wf", "واليس وفوتونا");
    arabicMap.put("ws", "ساموا");
    arabicMap.put("xk", "كوسوفو");
    arabicMap.put("ye", "اليمن");
    arabicMap.put("yt", "مايوت");
    arabicMap.put("za", "جنوب أفريقيا");
    arabicMap.put("zm", "زامبيا");
    arabicMap.put("zw", "زيمبابوي");
    arabicMap.put("ac", "جزيرة الصعود");
    arabicMap.put("ti", "تريستان دا كونها");
    arabicMap.put("bas", "باشكورتوستان");
    arabicMap.put("bia", "بيكيني أتول");
    arabicMap.put("bri", "بريتاني");
    arabicMap.put("bur", "بورياتيا");
    arabicMap.put("cri", "جمهورية إشكيريا الشيشانية");
    arabicMap.put("che", "جمهورية الشيشان");
    arabicMap.put("chu", "تشوفاشيا");
    arabicMap.put("crm", "القرم");
    arabicMap.put("dag", "داغستان");
    arabicMap.put("eai", "جزيرة الفصح");
    arabicMap.put("eu", "الاتحاد الأوروبي");
    arabicMap.put("her", "هيرم");
    arabicMap.put("ing", "إنغوشيا");
    arabicMap.put("kpr", "جمهورية كوبان الشعبية");
    arabicMap.put("kab", "قبردينو بلقاريا");
    arabicMap.put("kal", "كالميكيا");
    arabicMap.put("kar", "قراتشاي-شركيسيا");
    arabicMap.put("kkp", "كاراكالباكستان");
    arabicMap.put("krl", "كاريليا");
    arabicMap.put("kha", "خاكاسيا");
    arabicMap.put("kom", "كومي");
    arabicMap.put("ala", "ألاسكا");
  }
}